### ISSUE TITLE
Board Page - Thinking in React Step-1

### ISSUE THREAD

**Issue by ck-temp** [ck-temp/todo#1]
1. Analyse the dashboard page of the TODO application, similar to the Trello Board page ([https://trello.com/b/ZqN99gGN/agile-sprint-board](https://trello.com/b/ZqN99gGN/agile-sprint-board)) - only the Kanban Board.
2. For the above Board page, complete the 1st step mentioned in the blog "Thinking in React" ([https://reactjs.org/docs/thinking-in-react.html#step-1-break-the-ui-into-a-component-hierarchy](https://reactjs.org/docs/thinking-in-react.html#step-1-break-the-ui-into-a-component-hierarchy)).

**Comment by thirumalai56** [comment]
30/03/2020 - Status
Completed analyzed list of component going to use for board section.

**Comment by ck-temp** [comment]
@thirumalai56 - can you add the analyzed list of components in this comments.

**Comment by thirumalai56** [comment]
Today I have created PR for board related components

Components List:
1.Board component
2.Board list component
3.Add new list component
4.Card component
5.Add new card component
6.Edit new card component

Ref Screenshots:
![Board](https://user-images.githubusercontent.com/22026964/78134449-ce3aab80-743d-11ea-8913-bc3f42a8520b.png)

![board list](https://user-images.githubusercontent.com/22026964/78134468-d72b7d00-743d-11ea-8c4b-7638fe4dc52c.png)

![add new list](https://user-images.githubusercontent.com/22026964/78134505-e90d2000-743d-11ea-9098-f5699d7bbeb1.png)

![add new card](https://user-images.githubusercontent.com/22026964/78134568-02ae6780-743e-11ea-98ae-d606e42872b1.png)

![edit card](https://user-images.githubusercontent.com/22026964/78134605-0e019300-743e-11ea-84fb-ee85ae332e83.png)

**Comment by glad25** [comment]
Today I have worked on changes in folder structure and analysed about test case file configuration.

**Comment by thirumalai56** [comment]
06/04/2020 -Status
Created static board and card details section

**Comment by glad25** [comment]
07/04/20-work status
created modal popover component and working on responsive board section.

**Comment by thirumalai56** [comment]
07/04/2020-Status
Separated board and card related components,then pushed code changes

**Comment by thirumalai56** [comment]
08/04/2020-Status 
analyzing the board section drag and drop functionality for cards

**Comment by thirumalai56** [comment]
@ck-temp This issue has been completed, so please close this issue.
